# Site settings
name: Atomix
email: louishwh@gmail.com
author: louis han
url: http://www.louishwh.top

github: https://github.com/louishwh/
baseurl: ""
description: Seeking truth from facts.
meta_description: Atomix
motto: Seeking truth from facts.
banner: The unity of knowledge and actionã€‚

permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: louishwh

# Build settings
markdown: kramdown

baidu_analysis: 624f97ab37fd73fbedc7929427ca95ea

